# Generated by Django 3.0.4 on 2020-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('ability', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=200)),
                ('resp', models.CharField(max_length=500)),
            ],
        ),
    ]
