# Generated by Django 3.0.4 on 2020-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=1000)),
                ('work2', models.CharField(max_length=1000)),
                ('work3', models.CharField(max_length=1000)),
                ('work4', models.CharField(max_length=1000)),
                ('work5', models.CharField(max_length=5000)),
                ('sskill', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='ability',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='interest',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resp',
            field=models.CharField(max_length=5000),
        ),
    ]
